name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: node.js v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
